### ISSUE TITLE
Can't resolve '@std/path/posix'

### ISSUE THREAD

**Issue by geraintwhite** [elecdeer/storybook-addon-source-link#34]
Since upgrading from 0.2.1 to 0.2.2 we are now facing a compilation error:

<img width="937" height="137" alt="Image" src="https://github.com/user-attachments/assets/71364cde-8a1f-4e09-8cc5-bccbf50e0200" />

It appears that `@std/path` isn't being bundled correctly as per https://github.com/elecdeer/storybook-addon-source-link/pull/15#discussion_r2225761573

**Comment by elecdeer** [comment]
I thought there was no problem because it bundles correctly when I build it locally. 
However, it seems that the code published to npm is not bundled.

I will investigate this now.

**Comment by elecdeer** [comment]
@geraintwhite 
The cause was that it wasn't bundled correctly. 
I believe this is fixed in v0.2.3, so please give it a try.
